version: "3.7"
services:
  postgres-db:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admlocal1
    hostname: 0.0.0.0
    ports:
      - "5432:5432"
  java-db-app:
    container_name: todo-backend
    image: todo-backend
    ports:
      - "8081:8080"
    depends_on:
      - database
