server:
  port: 8080

spring:
  application:
    name: Todo App Backend

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Admlocal1
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: default
      password: 90575e69-6fe9-4c72-93d4-4628f9c70c28

springdoc:
  swagger-ui:
    path: /