server:
  port: 8080

spring:
  application:
    name: Todo App Backend

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Admlocal1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  security:
    user:
      name: default
      password: 90575e69-6fe9-4c72-93d4-4628f9c70c28