server:
  port: 8080

spring:
  application:
    name: Todo App Backend

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Admlocal1
    driver-class-name: org.postgresql.Driver